name: Upload to S3
  runs-on: ubuntu-latest
    run: |
      aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'ap-southeast-1'